"""mkdocs hooks for the generated design-docs wiki.

Two jobs, both of which have to happen INSIDE mkdocs — they act on objects
(`File`, `Navigation`) that exist only after the staged tree has been read, so
they cannot be done in `stage.py`.

1.  `on_files` — repoint the "edit this page" link at the real source.

    `edit_uri` in mkdocs.yml is a single prefix that mkdocs appends the page's
    *staged* path to. Several classes of page have no source at that path —
    the landing page (staged from `00-INDEX.md`), the ADRs (from `docs/adr/`),
    the section landings staged from a `README.md`, and everything stage.py
    generates — and GitHub turns `edit/main/<path-that-does-not-exist>` into
    its NEW FILE editor, so the pencil icon invited a reader to create a
    second, divergent copy of a canonical document inside `docs/design/`. For
    the staged ADRs that is the sharp end: `docs/adr/` is Tier 1 authority
    (ADR-0001), and the wiki must never be the mechanism by which its own
    canon gets forked.

    Generated pages get `edit_uri = None` — no pencil at all — which is what
    mkdocs' own `File.edit_uri` docstring prescribes for generated files. The
    list comes from stage.py, so a new generated page cannot quietly reacquire
    a broken link.

2.  `on_nav` — restore the canonical reading order.

    There is deliberately no `nav:` block, so mkdocs orders by filename. That
    is right for `01-`..`07-` and wrong everywhere else, where it silently
    substitutes alphabetical order for an order the project treats as load-
    bearing: the sidebar listed the fourteen domains alphabetically while
    `reference/domains.md` — generated by this same build — listed them in
    §13.x order, i.e. infrastructure-then-agents, i.e. the canonical sentence
    in `02-constitution.md`.

    The order is not hand-authored here. It is read back out of the canonical
    chapters: `00-INDEX.md`'s chapter-map table gives the section order and
    the order within `programme/` and `ops/`, and `stage.py` writes the §13.x
    domain order it already scrapes into `build/nav-order.json`. Add a chapter
    to `docs/design/` and it still appears with no config change; it sorts by
    filename within its section until the index's chapter map mentions it.
"""

from __future__ import annotations

import json
import posixpath
from pathlib import Path
from typing import Any

HERE = Path(__file__).resolve().parent
NAV_ORDER = HERE / "build" / "nav-order.json"

# Staged prefix -> what the pencil should actually open, relative to the
# `edit_uri` prefix (`edit/main/docs/design/`). `None` means "generated: show
# no edit button at all", which is what mkdocs' own File.edit_uri docstring
# prescribes for generated files.
EDIT_REMAP = {
    "index.md": "00-INDEX.md",  # staged from 00-INDEX.md by stage.py transform 1
}
EDIT_PREFIX_REMAP = {
    "decisions/": "../adr/",  # staged from docs/adr/ by transform 7
}


def _authored_index_remap(order: dict[str, list[str]]) -> dict[str, str]:
    """`<section>/index.md` -> the authored README it was staged from.

    Derived from the set stage.py exports, never hand-listed here: a literal
    copy would be a second statement of the same fact, and the day someone adds
    `ops/README.md` the copy would be stale — the pencil on `/design/ops/` would
    point at a `docs/design/ops/index.md` that does not exist, i.e. C1's
    new-file-editor defect, returned for that one page with nothing to catch it.
    """
    remap = {}
    for section in order.get("authored_sections", []):
        source = f"{section}/README.md"
        # Sections staged in from elsewhere resolve through the same prefix map
        # the chapters use, so the pencil follows the file, not the mount point.
        for prefix, replacement in EDIT_PREFIX_REMAP.items():
            if source.startswith(prefix):
                source = replacement + source[len(prefix) :]
                break
        remap[f"{section}/index.md"] = source
    return remap


def on_files(files: Any, config: Any) -> Any:
    """Point every edit link at a path that actually exists, or at nothing."""
    # Both sets come from stage.py rather than being pattern-matched or
    # hand-listed here, so neither a new generated page nor a new authored
    # section index can quietly reacquire a broken edit link.
    order = _load_order()
    generated = set(order["generated"])
    remap = {**EDIT_REMAP, **_authored_index_remap(order)}
    for f in files:
        src = f.src_uri
        if not src.endswith(".md"):
            continue
        if src in generated:
            f.edit_uri = None
            continue
        if src in remap:
            f.edit_uri = remap[src]
            continue
        for prefix, replacement in EDIT_PREFIX_REMAP.items():
            if src.startswith(prefix):
                f.edit_uri = replacement + src[len(prefix) :]
                break
    return files


def _load_order() -> dict[str, list[str]]:
    """Canonical orders, scraped from the chapters by stage.py."""
    if not NAV_ORDER.is_file():
        raise SystemExit(f"hooks.py: {NAV_ORDER} missing — run stage.py (via build.sh) before mkdocs")
    data: dict[str, list[str]] = json.loads(NAV_ORDER.read_text(encoding="utf-8"))
    return data


def _key_for(item: Any, order: list[str]) -> tuple[int, str]:
    """Sort key: position in the canonical list, then filename for anything the
    canon does not mention (a new chapter keeps working, it just sorts last)."""
    if item.is_page:
        name = posixpath.basename(item.file.src_uri)
        directory = posixpath.dirname(item.file.src_uri)
    else:
        # A Section: identify it by the directory its first page lives in.
        first = _first_page(item)
        if first is None:
            return (len(order), item.title or "")
        directory = posixpath.dirname(first.file.src_uri)
        name = directory.split("/")[0] + "/"
        return (order.index(name) if name in order else len(order), name)
    key = f"{directory}/{name}" if directory else name
    return (order.index(key) if key in order else len(order), key)


def _first_page(item: Any) -> Any:
    for child in getattr(item, "children", None) or []:
        if child.is_page:
            return child
        found = _first_page(child)
        if found is not None:
            return found
    return None


def _sort(items: Any, order: list[str]) -> None:
    items.sort(key=lambda i: _key_for(i, order))
    for item in items:
        if getattr(item, "children", None):
            _sort(item.children, order)


def _flatten_pages(items: Any) -> list[Any]:
    """Every page under `items`, in nav order, depth-first."""
    pages = []
    for item in items:
        if item.is_page:
            pages.append(item)
        elif getattr(item, "children", None):
            pages.extend(_flatten_pages(item.children))
    return pages


def _relink(nav: Any) -> None:
    """Rebuild `nav.pages` and the prev/next/parent links from the sorted tree.

    mkdocs computes these in `get_navigation()`, which runs BEFORE `on_nav` —
    so re-sorting `nav.items` alone left the footer Previous/Next walking the
    old filename order while the sidebar showed the canonical one. Two surfaces
    of the same reading order, disagreeing: the exact defect on_nav exists to
    fix, one click away.

    Reimplemented here rather than importing mkdocs' `_get_by_type` /
    `_add_previous_and_next_links` / `_add_parent_links`: those are private
    symbols with no stability guarantee, and the logic is a three-line walk.
    `build.sh` pinning mkdocs would make the import tolerable, but not needing
    the pin to hold is better. `nav.pages` also feeds sitemap.xml, where the
    order is cosmetic.
    """
    pages = _flatten_pages(nav.items)
    nav.pages = pages
    bookends: list[Any] = [None, *pages, None]
    for previous, page, following in zip(bookends[:-2], pages, bookends[2:], strict=True):
        page.previous_page, page.next_page = previous, following

    def set_parents(items: Any, parent: Any = None) -> None:
        for item in items:
            item.parent = parent
            if getattr(item, "children", None):
                set_parents(item.children, item)

    set_parents(nav.items)


def on_nav(nav: Any, config: Any, files: Any) -> Any:
    """Reorder the derived nav into the order the chapters themselves declare."""
    _sort(nav.items, _load_order()["order"])
    _relink(nav)
    return nav
